using APBD_TASK2.Enums;
using APBD_TASK2.Exceptions;

namespace APBD_TASK2.Models;

/// <summary>
/// The common concept shared by every rentable device. It is <c>abstract</c>
/// on purpose: the system never owns a plain "Equipment", only concrete kinds
/// of it (<see cref="Laptop"/>, <see cref="Projector"/>, <see cref="Camera"/>).
///
/// The class owns its own status state-machine. Keeping the transition rules
/// here (instead of letting services flip the status field directly) gives the
/// type high cohesion: everything about an equipment's state lives in one place,
/// and an illegal transition is impossible to express.
/// </summary>
public abstract class Equipment
{
    private static int _nextId = 1;

    /// <summary>Unique identifier generated by the system.</summary>
    public int Id { get; }

    public string Name { get; }

    public EquipmentStatus Status { get; private set; } = EquipmentStatus.Available;

    protected Equipment(string name)
    {
        if (string.IsNullOrWhiteSpace(name))
            throw new ArgumentException("Equipment name must not be empty.", nameof(name));

        Id = _nextId++;
        Name = name.Trim();
    }

    public bool IsAvailable => Status == EquipmentStatus.Available;

    public void MarkAsRented()
    {
        if (Status != EquipmentStatus.Available)
            throw new InvalidEquipmentStateException(Id, Name, Status, "rent");

        Status = EquipmentStatus.Rented;
    }

    public void MarkAsReturned()
    {
        if (Status != EquipmentStatus.Rented)
            throw new InvalidEquipmentStateException(Id, Name, Status, "return");

        Status = EquipmentStatus.Available;
    }

    /// <summary>Take the item out of service, e.g. because of damage or maintenance.</summary>
    public void MarkAsUnavailable()
    {
        if (Status == EquipmentStatus.Rented)
            throw new InvalidEquipmentStateException(Id, Name, Status, "mark as unavailable");

        Status = EquipmentStatus.Unavailable;
    }

    /// <summary>Bring the item back into service after maintenance.</summary>
    public void MarkAsAvailable()
    {
        if (Status == EquipmentStatus.Rented)
            throw new InvalidEquipmentStateException(Id, Name, Status, "mark as available");

        Status = EquipmentStatus.Available;
    }

    /// <summary>
    /// A human readable description. <c>virtual</c> so the base supplies a sensible
    /// default and every concrete type extends it with its own specifics.
    /// </summary>
    public virtual string GetDescription() => $"[#{Id}] {Name} ({GetType().Name}) - {Status}";
}
